Controller/AdminAbstractConfigurationController.php
<?php

namespace Smirik\PropelAdminBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Smirik\PropelAdminBundle\DataGrid\DataGrid;

abstract class AdminAbstractConfigurationController extends Controller
{
    /**
     * @var \Smirik\PropelAdminBundle\DataGrid\DataGrid $grid
     */
    public $grid;

    /**
     * @var integer $page
     */
    protected $page = 1;
    /**
     * @var integer $limit
     */
    protected $limit = 15;

    /**
     * @var string
     */
    public $layout = '::base.html.twig';
    
    /**
     * @var mixed
     */
    public $object;
    /**
     * @var string
     */
    public $name;

    /**
     * @var array
     */
    protected $routes = array();

    public function __construct()
    {
        $this->generateRoutes();
    }
    
    public function generateRoutes()
    {
        $this->routes = array(
            'index'  => 'admin_'.$this->name.'_index',
            'list'   => 'admin_'.$this->name.'_list',
            'new'    => 'admin_'.$this->name.'_new',
            'create' => 'admin_'.$this->name.'_create',
            'edit'   => 'admin_'.$this->name.'_edit',
            'update' => 'admin_'.$this->name.'_edit',
            'delete' => 'admin_'.$this->name.'_delete',
            'enable' => 'admin_'.$this->name.'_enable',
        );
    }

    public function loadConfig()
    {
        $tmp    = explode('\\', get_class($this));
        $class  = $tmp[count($tmp) - 1];
        $this->get('admin.data.grid')->load($this->bundle, $class);
    }

    public function setup()
    {
        $this->loadConfig();
        if (array_key_exists('AvalancheImagineBundle', $this->container->getParameter('kernel.bundles'))) {
            $this->get('admin.data.grid')->setupAvalanche();
        }
    }

    public function getPaginate()
    {
        $this->page  = $this->getRequest()->query->get('page', false);
        $this->limit = $this->getRequest()->query->get('limit', false);
        
        if (!$this->limit) {
            $this->limit = $this->get('admin.data.grid')->getLimit();
        }
    }

    public function getObject()
    {
    }

    abstract public function getQuery();

    abstract public function getForm();

    public function initialize()
    {
        $this->setup();
        $this->generateRoutes();
    }

}

Resources/views/Admin/index.html.twig
{% extends layout %}

{% block content %}
    <h1>{{ 'List of'|trans }}
        <small>{{ name|trans }}</small>
    </h1>

    <div class="row">
        <div class="span12">
            <div class="alert-place">
            </div>
            <div class="progress progress-striped active">
                <div class="bar" style="width: 100%;"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div id="content" class="span12">
        </div>
    </div>

{% endblock %}

{% block javascripts %}

    {{ parent() }}
    {% javascripts
    '@SmirikPropelAdminBundle/Resources/public/js/tomodal.js' %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
    <script type="text/javascript">
        var default_route = '{{ path(routes.list, {"page": page, "sort": sort, "sort_type" : sort_type, "filter" : filter, "options": options}) }}';
        var default_error_message = "{{ 'Try again later'|trans }}.";
        var default_error_title = "{{ 'Error'|trans }}!";
        var default_confirm_message = "{{ 'Are you sure'|trans }}?";
    </script>
{% endblock %}

Resources/views/Admin/index_content.html.twig
{% include grid.template('list.single_actions') with {'grid': grid, 'routes': routes, 'page': page, 'sort': sort, 'sort_type': sort_type} %}
<form action="{{ path(routes.index, {'page': page, 'sort': sort, 'sort_type' : sort_type }) }}" name="filterable-form"
      method="get" class="filterable">
    <table class="table table-striped table-condensed table-bordered propel-admin">
        {% include grid.template('list.table_header') with {'columns': columns, 'routes': routes, 'page': page, 'sort': sort, 'sort_type': sort_type, 'options': options} %}
        {% include grid.template('list.table_filters') with {'columns': columns, 'routes': routes, 'page': page, 'sort': sort, 'sort_type': sort_type, 'options': options, 'filter_raw': filter_raw} %}
        {% for item in collection %}
            {% include grid.template('row') with { 'item': item, 'columns': columns, 'actions': actions, 'page': page, 'grid': grid, 'options': options } %}
        {% endfor %}

    </table>
</form>

{% include grid.template('list.mass_actions') with {'grid': grid} %}
{% include grid.template('list.paginate') with {'routes': routes, 'page': page, 'sort': sort, 'sort_type': sort_type, 'filter': filter, 'options': options, 'collection': collection} %}

Resources/views/Admin/row.html.twig
<tr id="object{{ item.id }}" data-id="{{ item.id }}">
    <td class="filter-checkbox"><input type="checkbox" class="admin_item_checkbox" data-item="{{ item.__toString() }}" name="checkbox[]" id="checkbox{{ item.id }}" value="{{ item.id }}"></td>
    {% for column in columns %}
        {% if column.listable %}
            <td class="column-{{ column.name }} column-type-{{ column.type }} propel-admin-object-action">
                {% if column.type == 'collection' %}
                    {% set coll = attribute(item, column.getter) %}
                    {% for item in coll %}
                        {{ item }}
                    {% endfor %}
                {% else %}
                    {% include column.template('list') with {"item": item, "column": column } %}
                {% endif %}
            </td>
        {% endif %}
    {% endfor %}

    {% if not options.hide_actions is defined or (options.hide_actions is defined and not options.hide_actions) %}
        {% for action in grid.actions.getByType('object')  %}
            {% include action.template with {'action': action, 'item': item } %}
        {% endfor %}

        <td class="propel-admin-native-action">
            <div class="btn-group">
                {% for action in grid.nativeActions.getByType('object')  %}
                    <a class="btn {% if action.label == 'Delete' %}btn-danger{% endif %}"
                       href="{{ path(action.route, { 'id': item.id }) }}">
                        {% if action.label == 'Delete' %}
                            <i class="icon-remove"></i>
                        {% elseif action.label == 'Edit'%}
                            <i class="icon-edit"></i>
                        {% else %}
                        <i class="icon-align-left"></i>
                        {% endif %}
                    </a>
                {% endfor %}
            </div>
        </td>
    {% endif %}
</tr>